export const REQUEST_STATE = {
  IDLE: 'IDLE',
  PENDING: 'PENDING',
  FULFILLED: 'FULFILLED',
  REJECTED: 'REJECTED',

  WRITING: 'WRITING',
  READING: 'READING',

  LOGGEDOUT: 'LOGGEDOUT',
  LOGGEDIN: 'LOGGEDIN',
}
