export const REQUEST_STATE = {
  IDLE: 'IDLE',
  PENDING: 'PENDING',
  FULFILLED: 'FULFILLED',
  REJECTED: 'REJECTED',

  WRITING: 'WRITING',
  READING: 'READING',
  UPDATED: 'UPDATED',

  LOGGEDOUT: 'LOGGEDOUT',
  LOGGINGOUT: 'LOGGINGOUT',
  LOGGINGIN: 'LOGGINGIN',
  LOGGEDIN: 'LOGGEDIN',
}
